---

quiet: true

skip-check:
- CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
- CKV_DOCKER_6 # Ensure that LABEL maintainer is used instead of MAINTAINER (deprecated)
- CKV_GHA_7 # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty.
- CKV2_GHA_1 # Ensure top-level permissions are not set to write-all
