# It is triggered on pushes to branches other than main and release branches.
# The workflow uses the `netcracker/qubership-workflow-hub/actions/maven-snapshot-deploy` action to perform the deployment.
# Please read the documentation on how to configure pom.xml for the deployment to work properly:
# https://github.com/netcracker/qubership-workflow-hub/blob/main/docs/maven-publish-pom-preparation_doc.md

name: Maven Build

on:
  push:
    branches-ignore:
      - "main"
      - "**release*"
      - "prettier/**"
      - "dependabot/**"
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch: {}
permissions:
  packages: write # Required for GitHub packages deployment. For maven central deployment it can be ommited
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy Maven Snapshot
        uses: netcracker/qubership-workflow-hub/actions/maven-snapshot-deploy@240ec0b6bab8629f663b0c779ee280b257f454c0 # main
        with:
          java-version: '21' # Specify the Java version to use for the build
          target-store: 'github' # or 'central' for Maven Central repository
          maven-command: 'package' # Relevant for action versions > v1.0.3 or main. By default maven-command == deploy
          additional-mvn-args: '' # Additional arguments to pass to mvn command
          maven-username: ${{ github.actor }} # For maven central repository it would be ${{ secrets.MAVEN_USER }}
          maven-token: ${{ github.token }} # For maven central repository it would be ${{ secrets.MAVEN_PASSWORD}}
          # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Organization level secret. Already set for Netcracker. Required only if target-store is 'central'
          # gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }} # Organization level secret. Already set for Netcracker.  Required only if target-store is 'central'
